# Site
name: 'ResNet'
description: ''
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'coding@iitgn.ac.in'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Jayakrishna Sahit:
      name:           Jayakrishna Sahit
      site:           https://sahitpj.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Jayakrishna Sahit, secretary of metis and here I present to you ResNet! Do get in touch to collaborate!"
      email:          jayakrishna.sahit@iitgn.ac.in
      twitter:        https://twitter.com/sahitpj

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]